// Package models provides domain types used across the application.
// The database-layer models are generated by sqlc in internal/db/dbq.
// This package holds higher-level types and configuration structures.
package models

// DeployRequest represents an incoming deployment request.
type DeployRequest struct {
	ProductName string
	StackName   string
	Mode        string   // "ansible", "compose", or "helm"
	HostIDs     []int64
	Config      map[string]string
}

// DeployResult holds the outcome of a deployment execution.
type DeployResult struct {
	Success bool
	Log     string
}

// AppConfig holds application-level configuration loaded from
// environment variables or config.yaml.
type AppConfig struct {
	DBPath        string `yaml:"db_path"`
	Port          string `yaml:"port"`
	DeployDir     string `yaml:"deploy_dir"`
	MasterKeyPath string `yaml:"master_key_path"`
}
