// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counts.sql

package dbq

import (
	"context"
)

const countDeployments = `-- name: CountDeployments :one
SELECT COUNT(*) FROM deployments
`

func (q *Queries) CountDeployments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeployments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHosts = `-- name: CountHosts :one
SELECT COUNT(*) FROM hosts
`

func (q *Queries) CountHosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}
