// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package dbq

import (
	"context"
	"database/sql"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (name, type, target_name, mode, host_ids, config, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, target_name, mode, host_ids, config, status, log, git_pushed, created_at, updated_at
`

type CreateDeploymentParams struct {
	Name       string
	Type       string
	TargetName string
	Mode       string
	HostIds    string
	Config     sql.NullString
	Status     string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.Name,
		arg.Type,
		arg.TargetName,
		arg.Mode,
		arg.HostIds,
		arg.Config,
		arg.Status,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.TargetName,
		&i.Mode,
		&i.HostIds,
		&i.Config,
		&i.Status,
		&i.Log,
		&i.GitPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, name, type, target_name, mode, host_ids, config, status, log, git_pushed, created_at, updated_at FROM deployments WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeployment(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.TargetName,
		&i.Mode,
		&i.HostIds,
		&i.Config,
		&i.Status,
		&i.Log,
		&i.GitPushed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, name, type, target_name, mode, host_ids, config, status, log, git_pushed, created_at, updated_at FROM deployments ORDER BY created_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.TargetName,
			&i.Mode,
			&i.HostIds,
			&i.Config,
			&i.Status,
			&i.Log,
			&i.GitPushed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentGitPushed = `-- name: SetDeploymentGitPushed :exec
UPDATE deployments SET git_pushed = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SetDeploymentGitPushed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDeploymentGitPushed, id)
	return err
}

const updateDeploymentLog = `-- name: UpdateDeploymentLog :exec
UPDATE deployments SET log = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateDeploymentLogParams struct {
	Log sql.NullString
	ID  int64
}

func (q *Queries) UpdateDeploymentLog(ctx context.Context, arg UpdateDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentLog, arg.Log, arg.ID)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.ID)
	return err
}
