// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package dbq

import (
	"context"
	"database/sql"
)

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (name, ip, ssh_user, ssh_port, ssh_key, tags)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, ip, ssh_user, ssh_port, ssh_key, tags, created_at
`

type CreateHostParams struct {
	Name    string
	Ip      string
	SshUser string
	SshPort int64
	SshKey  sql.NullString
	Tags    sql.NullString
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, createHost,
		arg.Name,
		arg.Ip,
		arg.SshUser,
		arg.SshPort,
		arg.SshKey,
		arg.Tags,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.SshUser,
		&i.SshPort,
		&i.SshKey,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHost = `-- name: DeleteHost :exec
DELETE FROM hosts WHERE id = ?
`

func (q *Queries) DeleteHost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHost, id)
	return err
}

const getHost = `-- name: GetHost :one
SELECT id, name, ip, ssh_user, ssh_port, ssh_key, tags, created_at FROM hosts WHERE id = ? LIMIT 1
`

func (q *Queries) GetHost(ctx context.Context, id int64) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.SshUser,
		&i.SshPort,
		&i.SshKey,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, name, ip, ssh_user, ssh_port, ssh_key, tags, created_at FROM hosts ORDER BY created_at DESC
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.SshUser,
			&i.SshPort,
			&i.SshKey,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
