// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"database/sql"
)

type Deployment struct {
	ID         int64
	Name       string
	Type       string
	TargetName string
	Mode       string
	HostIds    string
	Config     sql.NullString
	Status     string
	Log        sql.NullString
	GitPushed  sql.NullBool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Host struct {
	ID        int64
	Name      string
	Ip        string
	SshUser   string
	SshPort   int64
	SshKey    sql.NullString
	Tags      sql.NullString
	CreatedAt sql.NullTime
}

type Product struct {
	ID          int64
	Name        string
	DisplayName string
	Description sql.NullString
	Version     sql.NullString
	Icon        sql.NullString
	Modes       string
}

type Setting struct {
	Key   string
	Value string
}

type Stack struct {
	ID          int64
	Name        string
	DisplayName string
	Description sql.NullString
	Products    string
}
