// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbq

import (
	"context"
	"database/sql"
)

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, display_name, description, version, icon, modes FROM products WHERE name = ? LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Version,
		&i.Icon,
		&i.Modes,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, display_name, description, version, icon, modes FROM products ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Version,
			&i.Icon,
			&i.Modes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (name, display_name, description, version, icon, modes)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    display_name = excluded.display_name,
    description = excluded.description,
    version = excluded.version,
    icon = excluded.icon,
    modes = excluded.modes
`

type UpsertProductParams struct {
	Name        string
	DisplayName string
	Description sql.NullString
	Version     sql.NullString
	Icon        sql.NullString
	Modes       string
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.ExecContext(ctx, upsertProduct,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Version,
		arg.Icon,
		arg.Modes,
	)
	return err
}
