// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stacks.sql

package dbq

import (
	"context"
	"database/sql"
)

const getStackByName = `-- name: GetStackByName :one
SELECT id, name, display_name, description, products FROM stacks WHERE name = ? LIMIT 1
`

func (q *Queries) GetStackByName(ctx context.Context, name string) (Stack, error) {
	row := q.db.QueryRowContext(ctx, getStackByName, name)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Products,
	)
	return i, err
}

const listStacks = `-- name: ListStacks :many
SELECT id, name, display_name, description, products FROM stacks ORDER BY name
`

func (q *Queries) ListStacks(ctx context.Context) ([]Stack, error) {
	rows, err := q.db.QueryContext(ctx, listStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stack
	for rows.Next() {
		var i Stack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStack = `-- name: UpsertStack :exec
INSERT INTO stacks (name, display_name, description, products)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    display_name = excluded.display_name,
    description = excluded.description,
    products = excluded.products
`

type UpsertStackParams struct {
	Name        string
	DisplayName string
	Description sql.NullString
	Products    string
}

func (q *Queries) UpsertStack(ctx context.Context, arg UpsertStackParams) error {
	_, err := q.db.ExecContext(ctx, upsertStack,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Products,
	)
	return err
}
