{{- if .Values.masterKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opswise.fullname" . }}-master-key
  labels:
    {{- include "opswise.labels" . | nindent 4 }}
type: Opaque
data:
  master.key: {{ .Values.masterKey.value | b64enc | quote }}
{{- end }}
